import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import {validateCatalog,moduleSelection} from '../client/core/catalog.mjs';

const custom=await fs.readFile(new URL('../src/renderer/custom-css.js',import.meta.url),'utf8');
const emoji=await fs.readFile(new URL('../src/renderer/personal-emoji.js',import.meta.url),'utf8');
const sidebarSource=await fs.readFile(new URL('../src/renderer/sidebar-productivity.js',import.meta.url),'utf8');
const navigationSource=await fs.readFile(new URL('../src/renderer/native-navigation.js',import.meta.url),'utf8');
const replyBootstrapSource=await fs.readFile(new URL('../src/renderer/reply-window-bootstrap.js',import.meta.url),'utf8');
const devSource=await fs.readFile(new URL('../scripts/dev.mjs',import.meta.url),'utf8');

test('Wave 3 power tools are independent and Sidebar Productivity shares passive cache observation',async()=>{
 const manifest=JSON.parse(await fs.readFile(new URL('../mods/runtime.json',import.meta.url))),catalog=validateCatalog(JSON.parse(await fs.readFile(new URL('../client/catalog.json',import.meta.url))),manifest.modules),slack=catalog.apps.find(app=>app.id==='slack');
 for(const id of ['slack-custom-css','slack-personal-emoji']){const selection=moduleSelection(slack,[id],manifest.modules),module=id==='slack-custom-css'?'custom-css':'personal-emoji';assert.equal(selection.disabled.includes(module),false);assert.equal(selection.disabled.includes('state-observer'),true);assert.equal(slack.mods.find(mod=>mod.id===id).defaultEnabled,false);}
 const sidebar=moduleSelection(slack,['slack-sidebar-productivity'],manifest.modules);assert.equal(sidebar.disabled.includes('sidebar-productivity'),false);assert.equal(sidebar.disabled.includes('state-observer'),false);assert.equal(sidebar.disabled.includes('native-navigation'),false);for(const id of ['triage-surface','native-reply','history-reader','mark-read'])assert.equal(sidebar.disabled.includes(id),true);
 assert.equal(slack.mods.find(mod=>mod.id==='slack-custom-css').settings[0].type,'textarea');assert.equal(slack.mods.find(mod=>mod.id==='slack-personal-emoji').settings[0].maxLength,8000);
 const sidebarMod=slack.mods.find(mod=>mod.id==='slack-sidebar-productivity');for(const key of ['unifiedEnabled','compactSidebar','autoHideSidebar','smallWindowSidebar','prewarmReply'])assert.ok(sidebarMod.settings.some(setting=>setting.key===key));assert.equal(sidebarMod.settings.some(setting=>setting.key==='sidebarMode'),false);assert.match(sidebarMod.access,/already mounted/);assert.match(sidebarMod.access,/never opens conversations/);assert.match(sidebarMod.access,/additional memory/);
});

test('Custom CSS applies validated text live and removes it completely',()=>{
 const nodes=new Map(),root={append(node){nodes.set(node.id,node);}},document={head:root,documentElement:root,getElementById:id=>nodes.get(id)||null,createElement:()=>({id:'',textContent:'',remove(){nodes.delete(this.id);}})},window={};
 vm.runInNewContext(custom,{window,location:{origin:'https://app.slack.com'},document});const api=window.__PME_CUSTOM_CSS__;
 assert.deepEqual({...api.configure({css:'.c-message { line-height: 1.35; }'})},{active:true,length:33});assert.equal(nodes.get('pme-custom-css-style').textContent,'.c-message { line-height: 1.35; }');assert.throws(()=>api.configure({css:'@import "https://bad.example/x.css"'}));api.dispose();assert.equal(nodes.size,0);assert.equal(window.__PME_CUSTOM_CSS__,undefined);
});

test('Personal Emoji and Sidebar Productivity keep bounded, reversible renderer lifecycles',async()=>{
 for(const fragment of ['referrerPolicy=\'no-referrer\'','loading=\'lazy\'','blockedSelector','names.length>11','markJumbo(','data-pme-personal-emoji-large','width:32px','registerProvider','providerEntries','value.length>1000','resolvedImages','safeURL(value)','restore()','observer.disconnect()','replaceWith(document.createTextNode','delete window.__PME_PERSONAL_EMOJI__'])assert.ok(emoji.includes(fragment),`missing personal emoji guard: ${fragment}`);
 assert.equal(emoji.includes('innerHTML'),false);assert.equal(emoji.includes('fetch('),false);assert.equal(emoji.includes('localStorage'),false);
 for(const fragment of ['__PME_OBSERVER__?.peek','__PME_OBSERVER__?.sidebarIndex','preview.text','Cached sidebar preview','Sidebar destination actions','No cached message preview is available yet.','!settings.peekEnabled&&!settings.openAction&&!settings.replyAction','__PME_NATIVE_NAVIGATION__?.destination','navigation?.open?.','navigation?.openDetached?.','separate Slack window','data-pme-sidebar-preview-avatar','unifiedEnabled','organizerEnabled','openAction','replyAction','prewarmReply','syncReplyWarmth','navigation.prewarm?.','releasePrewarm?.','hoverDelay','data-pme-unified-sidebar','data-pme-unified-list','nextRowHost=list.querySelector(MOUNTED_ROW)?.parentElement||list','nestedList','Unified Inbox','Classic view','mounted','starred','localStorage','data-pme-unified-dialog','New Unified Sidebar group','data-pme-unified-header-menu','Sidebar productivity menu','controls.append(switcher)','Group rules…','pme-unified-sidebar-rules','never workspace IDs, channel IDs','Apply groups to Slack…','nativePlan()','sweeper_button','channel_ctx_menu_move','Create and Add Channels','operations.length>200','No further organizer changes were attempted','Copy diagnostics','diagnosticSnapshot','overlapPairs','flex:0 0 34px','unified?0:hiddenNow','dialog.showModal()','clearPreview()','observer.disconnect()','abort.abort()','delete window.__PME_UNIFIED_SIDEBAR__','delete window.__PME_SIDEBAR_PRODUCTIVITY__'])assert.ok(sidebarSource.includes(fragment),`missing sidebar productivity guard: ${fragment}`);
 for(const fragment of ['data-qa-channel-sidebar-channel-id','data-item-key','mounted(request)','control.click()','data-channel-id','data-thread-ts','function surface(','function current(','function openDetached(','function prewarm(','function releasePrewarm(','function settlePrewarm(','function layoutDiagnostics(','bodyScrollHeight','gridTemplateRows','registerWindowIdForwarder','window.open(hidden?\'about:blank\':url,frameName,features)','function installReplyBoot(','function prepareDetached(','function revealDetached(','function warmNavigate(','data-pme-reply-route','child.location.replace(url)','show=${idPromise?.then?\'no\':\'yes\'}','paintWhenInitiallyHidden=yes','callBrowserWindowMethod','disposition=desktop-window','preventScroll:true','delete window.__PME_NATIVE_NAVIGATION__'])assert.ok(navigationSource.includes(fragment),`missing native navigation guard: ${fragment}`);
 for(const fragment of ['__PME_REPLY_BOOTSTRAP__','data-pme-reply-bootstrap','data-pme-reply-window','data-pme-reply-delayed','location.origin!==\'https://app.slack.com\'','body>*{visibility:hidden!important}','p-ia4_top_nav','channel-sidebar','position:fixed!important;inset:0!important','grid-template-rows:minmax(0,1fr)','height:100vh','p-view_contents--primary','max-height:none!important','grid-template-columns:0 minmax(0,1fr)'])assert.ok(replyBootstrapSource.includes(fragment),`missing reply bootstrap guard: ${fragment}`);
 for(const fragment of ['target.url===\'about:blank\'','target.openerId','new URL(opener.url).origin===\'https://app.slack.com\'','Page.addScriptToEvaluateOnNewDocument','Prepared a dedicated Slack reply window before navigation.','Target.setDiscoverTargets'])assert.ok(devSource.includes(fragment),`missing pre-navigation reply discovery guard: ${fragment}`);
 assert.equal(replyBootstrapSource.includes('fetch('),false);assert.equal(replyBootstrapSource.includes('localStorage'),false);
 assert.equal(sidebarSource.includes('data-pme-unified-templates'),false);assert.equal(sidebarSource.includes('data-pme-unified-apply'),false);
 assert.equal(sidebarSource.includes('fetch('),false);assert.equal(sidebarSource.includes('setInterval('),false);assert.equal(sidebarSource.includes('prompt('),false);assert.equal(sidebarSource.includes('confirm('),false);
 const native=await fs.readFile(new URL('../native/TriageController.swift',import.meta.url),'utf8'),ui=await fs.readFile(new URL('../client/ui/app.js',import.meta.url),'utf8');for(const fragment of ['Slack Custom CSS','Personal Emoji','Sidebar Productivity','Enable Unified Sidebar','Show Hide controls for destinations and sections','Show Open action','Show Reply in new window action','Keep quick-reply window warm','does not change the Triage pill view','SettingsTextApplyButton','multilineInput'])assert.ok(native.includes(fragment),`missing native Wave 3 settings: ${fragment}`);assert.ok(ui.includes("setting.type==='textarea'"));
});

test('native Slack Settings repaints an opaque document instead of compositing stale scroll buffers',async()=>{
 const native=await fs.readFile(new URL('../native/TriageController.swift',import.meta.url),'utf8');for(const fragment of ['scroll.drawsBackground=true','scroll.contentView.drawsBackground=true','document.layer?.backgroundColor=TriagePreferencesTheme.background.cgColor','document.setNeedsDisplay(document.bounds)','scroll.contentView.setNeedsDisplay(scroll.contentView.bounds)'])assert.ok(native.includes(fragment),`missing settings repaint contract: ${fragment}`);assert.equal(native.includes('copiesOnScroll'),false);
});
