'use strict';
const root=document.querySelector('#app'),toast=document.querySelector('#toast');let state=null,view='library',busy=false,pending=new Map(),sequence=0,toastTimer,renderedView,showIncompatible=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',plus:'M12 5v14M5 12h14',refresh:'M20 8a8 8 0 1 0 0 8M20 3v5h-5',chevron:'m9 5 7 7-7 7',play:'m8 5 11 7-11 7Z',stop:'M6 6h12v12H6Z',gear:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1ZM9 12a3 3 0 1 0 6 0 3 3 0 1 0-6 0',inbox:'M4 4h16l2 10v6H2v-6L4 4ZM2 14h6l2 3h4l2-3h6',check:'m5 12 4 4L19 6',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Zm-4 9 3 3 5-6',folder:'M3 5h6l3 3h9v12H3Z',info:'M12 8v.1M12 11v6M12 2a10 10 0 1 0 0 20 10 10 0 1 0 0-20',compose:'M12 4H4v16h16v-8M16 3l5 5-9 9H7v-5Z'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.grid}"/></svg>`;
const slack=()=>'<svg viewBox="0 0 24 24" aria-hidden="true"><g fill="#36c5f0"><rect x="1" y="8" width="10" height="4" rx="2"/><rect x="7" y="2" width="4" height="4" rx="2"/></g><g fill="#2eb67d"><rect x="13" y="1" width="4" height="10" rx="2"/><rect x="19" y="7" width="4" height="4" rx="2"/></g><g fill="#ecb22e"><rect x="13" y="13" width="10" height="4" rx="2"/><rect x="13" y="19" width="4" height="4" rx="2"/></g><g fill="#e01e5a"><rect x="7" y="13" width="4" height="10" rx="2"/><rect x="1" y="13" width="4" height="4" rx="2"/></g></svg>';
const spotify=()=>'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="#1ed760"/><g fill="none" stroke="#14251b" stroke-linecap="round"><path d="M6 9q6-3 13 1" stroke-width="1.9"/><path d="M7 12q5-2.5 11 1" stroke-width="1.7"/><path d="M8 15q4-1.8 9 1" stroke-width="1.6"/></g></svg>';
const appLogo=id=>id==='spotify'?spotify():slack();
function spotifyPreview(){return `<div class="mod-preview spotify-preview" aria-hidden="true"><div class="mini-player"><div class="mini-player-head">${spotify()}<span>NOW PLAYING</span></div><div class="mini-cover">♫</div><strong>Your next favorite</strong><small>Always within reach</small><div class="mini-playback">◀ <b>Ⅱ</b> ▶</div></div></div>`;}
function request(op,data={}){return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(Error('The client did not respond. Try reopening PME.'));},45000);pending.set(id,{resolve,reject,timer});if(window.webkit?.messageHandlers?.pme)window.webkit.messageHandlers.pme.postMessage({id,op,...data});else{clearTimeout(timer);pending.delete(id);reject(Error('Open this interface from the PimpMyElectron application.'));}});}
window.pmeReceive=response=>{const p=pending.get(response.id);if(!p)return;pending.delete(response.id);clearTimeout(p.timer);response.ok?p.resolve(response.result):p.reject(Error(response.error||'Action failed'));};
function notify(message){toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),9500);}
async function action(op,data={}){if(busy)return;busy=true;render();try{const result=await request(op,data);if(result?.apps)state=result;}catch(error){notify(error.message);}finally{busy=false;render();}}
function button(label,actionName,style='secondary',glyph){return `<button class="${style}" data-action="${actionName}" ${busy?'disabled':''}>${glyph?icon(glyph):''}${label}</button>`;}
function sidebar(){return `<aside class="sidebar"><div class="brand"><img src="icon.svg" alt="PME"><div><strong>PimpMyElectron</strong><small>Mod manager</small></div></div><button class="nav ${view==='library'?'active':''}" data-view="library">${icon('grid')}Your apps<span class="count">${state?.apps.filter(a=>a.installations.length).length||0}</span></button><div class="sidebar-label">SUPPORTED APPS</div>${(state?.apps||[]).map(a=>`<button class="nav ${view===a.id?'active':''}" data-view="${esc(a.id)}"><span class="slack-small">${appLogo(a.id)}</span>${esc(a.name)}${a.runtime.running?'<span class="count"><i class="dot"></i></span>':''}</button>`).join('')}<div class="sidebar-foot"><button class="nav ${view==='about'?'active':''}" data-view="about">${icon('info')}About PME</button><p>Local catalog · v${esc(state?.catalogVersion||'0.1.0')}</p></div></aside>`;}
function topbar(title){return `<header class="topbar"><span>Your apps</span>${title?`${icon('chevron')}<span>${esc(title)}</span>`:''}<div class="right">${button('Add app','add-app','quiet','plus')}${button(busy?'Working…':'Rescan','scan','quiet','refresh')}</div></header>`;}
function library(){return `<div class="content"><div class="heading"><div><div class="eyebrow">Your library</div><h1>Your apps. Your way.</h1><p>Choose an app, enable your mods, and make it yours.</p></div></div>${!state?'<div class="skeleton"></div>':`<div class="apps-grid">${state.apps.map(a=>`<button class="app-card" data-view="${esc(a.id)}"><div class="app-art">${appLogo(a.id)}</div><div class="app-card-info"><div class="title"><h2>${esc(a.name)}</h2><span class="tag ${a.installations.length?'green':''}">${a.runtime.running?'Running':a.installations.length?'Detected':'Not installed'}</span></div><p>${esc(a.description)}</p></div><div class="app-card-bottom"><span>${a.mods.length} bundled mod${a.mods.length!==1?'s':''} · ${a.installations.length} installation${a.installations.length!==1?'s':''}</span>${icon('chevron')}</div></button>`).join('')}</div><p class="library-note">PME supports Slack and Spotify, and looks in Applications and the Mac’s app index. Use Add app for an installation in another location.</p>`}</div><footer class="launchbar"><div class="launch-info"><strong>${busy?'Scanning supported apps…':'Ready when you are'}</strong><small>App bundles stay untouched.</small></div></footer>`;}
function preview(){return `<div class="mod-preview" aria-hidden="true"><div class="mini-strip"></div><div class="mini-inbox"><div class="mini-head">Design studio ${icon('compose')}</div><div class="mini-tabs"><b>Unread</b><span>Mentions</span><span>DMs</span><span>Threads</span></div>${[['AL','Alex',''],['#','design','gold'],['JR','Jordan','plum']].map(([initial,name,color])=>`<div class="mini-row"><div class="mini-avatar ${color}">${initial}</div><div class="mini-lines"><b>${name}</b><span></span><span></span></div><div class="mini-dot"></div></div>`).join('')}</div></div>`;}
function appView(app){const isSpotify=app.id==='spotify';const menuRunning=isSpotify&&(app.runtime.mods||['spotify-menu']).includes('spotify-menu'),cameraRunning=isSpotify&&app.runtime.mods?.includes('spotify-camera-pause');const visibleMods=app.mods.filter(m=>showIncompatible||m.compatible!==false);const selected=app.selectedMods.length,install=app.installations.find(i=>i.path===app.selectedPath),running=app.runtime.running;
 return `<div class="content"><div class="hero"><div class="hero-icon">${appLogo(app.id)}</div><div><h1>${esc(app.name)}</h1><p>${esc(app.description)}</p></div><div class="hero-meta"><span class="tag ${install?'green':''}">${running?'<i class="dot"></i>Running':install?'Ready to mod':'Choose an installation'}</span><small>${install?`v${esc(install.version)} · ${install.distribution==='direct-download'?'Direct download':'App Store'}`:'macOS'}</small></div></div>
 ${app.installations.length?`<div class="installation">${icon('folder')}<select id="installation" aria-label="${esc(app.name)} installation" ${busy||running?'disabled':''}>${app.installations.map(i=>`<option value="${esc(i.path)}" ${i.path===app.selectedPath?'selected':''} ${!i.verified?'disabled':''}>${esc(i.path)}${!i.verified?' — could not verify publisher':''}</option>`).join('')}</select><span>Installed app</span></div>`:`<div class="banner"><div><strong>${esc(app.name)} wasn’t found on this Mac.</strong><p>Add your installed ${esc(app.name)} app to get started.</p></div>${button('Find '+app.name+'…','add-app','secondary','folder')}</div>`}
 ${app.profileConflict?`<div class="banner"><div><strong>Bring your existing PME setup along.</strong><p>Choose your old PME project folder to reuse its settings and sign-ins.</p></div>${button('Import setup','import','secondary')}</div>`:''}
 ${app.changesPending?'<div class="banner"><div><strong>Mod selection changed</strong><p>Your running session is unchanged. Stop and relaunch to apply this selection.</p></div></div>':''}
 ${app.runtime.error?`<div class="banner">${esc(app.runtime.error)}</div>`:''}
 <div class="section-title"><h2>Available mods</h2><span>${visibleMods.length}</span><small>BUNDLED WITH PME</small><label class="compatibility-filter"><input type="checkbox" id="show-incompatible" ${showIncompatible?'checked':''}> Show incompatible</label></div>
 ${!visibleMods.length?'<p>No compatible mods for this platform. Turn on Show incompatible to explore available ports.</p>':''}${visibleMods.map(m=>`<article class="mod-card ${m.compatible===false?'incompatible':''}"><div class="mod-main"><div class="mod-heading"><div class="mod-mark">${icon('inbox')}</div><div><h3>${esc(m.name)}<span class="version">${esc(m.version)}</span></h3><div class="mod-author">by ${esc(m.author)} · ${esc(m.platforms.map(p=>({mac:'macOS',windows:'Windows',linux:'Linux',global:'All platforms'}[p])).join(', '))}</div></div><button class="toggle" role="switch" aria-checked="${app.selectedMods.includes(m.id)}" aria-label="Enable ${esc(m.name)}" data-mod="${esc(m.id)}" ${busy||m.compatible===false?'disabled':''}></button></div><p>${esc(m.description)}</p>${m.compatible===false?`<p class="incompatible-note">${esc(m.compatibilityReason)}</p>`:''}<div class="features">${m.features.slice(0,3).map(f=>`<div class="feature">${icon('check')}${esc(f)}</div>`).join('')}</div><button class="details-button" data-details="${esc(m.id)}">Explore this mod →</button>${m.id==='spotify-camera-pause'?`<button class="secondary" data-action="camera-settings" ${busy||!cameraRunning?'disabled':''}>Camera Pause settings…</button>${!cameraRunning?'<p class="setup-hint">Enable this mod and launch Spotify to choose apps.</p>':`<p class="setup-hint">${esc(app.runtime.cameraStatus)}</p>`}`:''}</div>${isSpotify?(m.id==='spotify-menu'?spotifyPreview():`<div class="mod-preview camera-preview" aria-hidden="true"><div><span>CAMERA ON</span><strong>Music takes a break.</strong><small>Back when you are.</small></div></div>`):preview()}<div class="mod-access">${icon('shield')}${esc(m.access)}</div></article>`).join('')}
 <section class="shortcuts"><div class="section-title"><h2>Manage shortcuts</h2><span>${(app.shortcuts||[]).length}</span></div><p>${app.shortcuts?.length?'Manage the apps you’ve saved for Finder, Spotlight, and the Dock.':'No shortcuts yet. Use Create shortcut below to save this installation and your selected mods as a launcher app.'}</p>
 ${(app.shortcuts||[]).map(p=>`<div class="shortcut-row"><div class="shortcut-info"><strong>${esc(p.name)}</strong><small>${esc(p.modIds.map(id=>app.mods.find(m=>m.id===id)?.name||id).join(', '))}</small><span title="${esc(p.shortcutPath)}">${esc(p.shortcutPath)}</span>${p.availability!=='available'?`<small class="shortcut-status">${p.availability==='missing'?'Not found at its saved location. If moved, launch it once to reconnect.':'Saved location is unavailable.'}</small>`:''}</div><div class="shortcut-actions">${(p.availability==='available'?[['shortcut-reveal','Reveal'],['shortcut-update','Update selection'],['shortcut-rename','Rename'],['shortcut-remove','Remove']]:[['shortcut-forget','Remove from list']]).map(([op,label])=>`<button class="quiet" data-shortcut="${esc(p.id)}" data-shortcut-op="${op}" ${busy?'disabled':''}>${label}</button>`).join('')}</div></div>`).join('')}
 </section>
 </div><footer class="launchbar"><div class="launch-info"><strong>${running?(isSpotify?'Spotify mods are enabled':app.runtime.signedIn?'Slack is running with PME':'Slack is running · sign in to begin'):`${selected} mod${selected===1?'':'s'} enabled`}</strong><small>${running?(isSpotify?(menuRunning?'Hover over Spotify in the menu bar':app.runtime.cameraStatus||'Camera Pause is running'):'Everyday mode · private local connection'):selected?(isSpotify?'Uses your existing Spotify session':'Launches in everyday mode'):'Enable a mod to launch with PME'}</small></div>${running?`<div class="session-actions">${isSpotify?'':button('Mod settings','mod-settings','quiet','gear')}${button(isSpotify?'Stop mods':'Stop Slack','stop','quiet','stop')}</div>`:''}<div class="launch-actions"><button class="secondary shortcut-callout" data-action="shortcut-create" ${busy||!selected||!install?'disabled':''}>${icon('plus')}Create shortcut…</button>${running?button(isSpotify?(menuRunning?'Open player':'Camera settings'):'Open inbox','show','primary',isSpotify?'play':'inbox'):`<button class="primary" data-action="launch" ${busy||!selected||!install||app.profileConflict?'disabled':''}>${icon('play')}${busy?'Working…':'Launch '+esc(app.name)}</button>`}</div></footer>`;
}
function about(){return `<div class="content"><div class="about"><div class="eyebrow">PimpMyElectron</div><h1>A home for your app mods.</h1><p>macOS client · ${esc(state?.clientVersion||'…')} (build ${esc(state?.clientBuild||'…')})</p><div class="about-row"><strong>Bundled catalog</strong><p>Supported apps and their mods ship with this version of PME. This build does not download or run mods from third-party catalogs.</p></div><div class="about-row"><strong>Your original apps stay intact</strong><p>PME launches the official app and adds the selected mods for that session. Closing PME leaves a running Slack session available. Stop Slack from its app page to end the session.</p></div><div class="about-row"><strong>A separate Slack sign-in</strong><p>The Slack adapter uses a separate profile. Sign in once inside the PME-launched Slack, or import your existing PME setup on this Mac. Your normal Slack profile is not copied.</p></div><div class="about-row"><strong>Everyday mode</strong><p>The client always uses the existing everyday launcher. Developer evaluation, screenshots, and network experiments are disabled. Spotify uses its native macOS playback controls without a debugging connection. Only the mods bundled with this app are available.</p></div><div class="about-row"><strong>Client updates</strong><p>PME checks daily while the manager is running. Updates install only when you choose. Stop mods and quit managed app sessions before installation. Automatic checks can be changed in the PimpMyElectron menu.</p>${button('Check for Updates…','update-check','secondary','refresh')}</div><div class="about-actions">${button('Import existing setup','import','secondary','folder')}${button('Open data folder','data-folder','quiet','folder')}</div></div></div><footer class="launchbar"><div class="launch-info"><strong>Made for a workflow that fits.</strong><small>Apple Silicon · macOS 13.3+</small></div></footer>`;}
function render(){const scroll=renderedView===view?(root.querySelector('.content')?.scrollTop||0):0;const app=state?.apps.find(a=>a.id===view);root.innerHTML=`<div class="shell">${sidebar()}<main class="main">${topbar(app?.name||(view==='about'?'About PME':''))}${app?appView(app):view==='about'?about():library()}</main></div>`;const content=root.querySelector('.content');if(content)content.scrollTop=scroll;renderedView=view;}
root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.view){view=b.dataset.view;render();return;}const app=state?.apps.find(a=>a.id===view)||state?.apps[0];if(b.dataset.shortcut){void action(b.dataset.shortcutOp,{appId:app.id,profileId:b.dataset.shortcut});return;}if(b.dataset.mod){const selected=new Set(app.selectedMods);selected.has(b.dataset.mod)?selected.delete(b.dataset.mod):selected.add(b.dataset.mod);void action('select',{appId:app.id,modIds:[...selected]});return;}
 if(b.dataset.details){const mod=app.mods.find(m=>m.id===b.dataset.details),d=document.createElement('dialog');d.innerHTML=`<h2>${esc(mod.name)}</h2><p>${esc(mod.description)}</p><div class="features">${mod.features.map(f=>`<div class="feature">${icon('check')}${esc(f)}</div>`).join('')}</div><p>${esc(mod.access)}</p><footer><button class="primary">Done</button></footer>`;document.body.append(d);d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();return;}
 const op=b.dataset.action;if(!op)return;const map={'show':'show','mod-settings':'show','camera-settings':'show'};
 void action(map[op]||op,{...(app?{appId:op==='import'?'slack':app.id}:{}),...(op==='show'?{view:'queue'}:op==='mod-settings'?{view:'preferences'}:op==='camera-settings'?{view:'camera-settings'}:{})});});
root.addEventListener('change',event=>{if(event.target.id==='show-incompatible'){showIncompatible=event.target.checked;render();return;}if(event.target.id==='installation')void action('select',{appId:view,installationPath:event.target.value});});
render();void action('scan');
setInterval(async()=>{if(busy||document.querySelector('dialog[open]')||document.activeElement?.matches('select'))return;try{const next=await request('status');if(JSON.stringify(next)!==JSON.stringify(state)){state=next;render();}}catch{}},2500);
