'use strict';
const root=document.querySelector('#app'),toast=document.querySelector('#toast');let state=null,view='library',busy=false,pending=new Map(),sequence=0,toastTimer,renderedView,showIncompatible=false,history=null,historyError=null,aboutTab='overview',feedbackPanel=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',plus:'M12 5v14M5 12h14',refresh:'M20 8a8 8 0 1 0 0 8M20 3v5h-5',chevron:'m9 5 7 7-7 7',play:'m8 5 11 7-11 7Z',stop:'M6 6h12v12H6Z',gear:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1ZM9 12a3 3 0 1 0 6 0 3 3 0 1 0-6 0',inbox:'M4 4h16l2 10v6H2v-6L4 4ZM2 14h6l2 3h4l2-3h6',check:'m5 12 4 4L19 6',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Zm-4 9 3 3 5-6',folder:'M3 5h6l3 3h9v12H3Z',info:'M12 8v.1M12 11v6M12 2a10 10 0 1 0 0 20 10 10 0 1 0 0-20',compose:'M12 4H4v16h16v-8M16 3l5 5-9 9H7v-5Z',quote:'M7 7h4v5H8l-2 4M14 7h4v5h-3l-2 4',wand:'m4 20 10-10M14 4l1 3 3 1-3 1-1 3-1-3-3-1 3-1ZM19 14l.7 1.6L21 16l-1.3.7L19 19l-.7-2.3L16 16l2.3-.4Z',palette:'M12 3a9 9 0 1 0 0 18h1.5a2 2 0 0 0 0-4H12a2 2 0 0 1 0-4h4a5 5 0 0 0 0-10ZM7 10h.1M9 6h.1M14 6h.1M17 9h.1',code:'m8 8-4 4 4 4M16 8l4 4-4 4M14 5l-4 14',smile:'M8 14s1.5 2 4 2 4-2 4-2M9 9h.1M15 9h.1M12 2a10 10 0 1 0 0 20 10 10 0 1 0 0-20',sidebar:'M4 4h16v16H4ZM10 4v16M6.5 8h1M6.5 12h1M6.5 16h1',layout:'M4 4h16v16H4ZM4 9h16M9 9v11',music:'M9 18V6l10-2v12M9 18a3 2 0 1 1-3-2 3 2 0 0 1 3 2ZM19 16a3 2 0 1 1-3-2 3 2 0 0 1 3 2',camera:'M4 7h4l2-2h4l2 2h4v12H4ZM12 10a3 3 0 1 0 0 6 3 3 0 1 0 0-6'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.grid}"/></svg>`;
const slack=()=>'<svg viewBox="0 0 24 24" aria-hidden="true"><g fill="#36c5f0"><rect x="1" y="8" width="10" height="4" rx="2"/><rect x="7" y="2" width="4" height="4" rx="2"/></g><g fill="#2eb67d"><rect x="13" y="1" width="4" height="10" rx="2"/><rect x="19" y="7" width="4" height="4" rx="2"/></g><g fill="#ecb22e"><rect x="13" y="13" width="10" height="4" rx="2"/><rect x="13" y="19" width="4" height="4" rx="2"/></g><g fill="#e01e5a"><rect x="7" y="13" width="4" height="10" rx="2"/><rect x="1" y="13" width="4" height="4" rx="2"/></g></svg>';
const spotify=()=>'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="11" fill="#1ed760"/><g fill="none" stroke="#14251b" stroke-linecap="round"><path d="M6 9q6-3 13 1" stroke-width="1.9"/><path d="M7 12q5-2.5 11 1" stroke-width="1.7"/><path d="M8 15q4-1.8 9 1" stroke-width="1.6"/></g></svg>';
const appLogo=id=>id==='spotify'?spotify():slack();
function spotifyPreview(){return `<div class="mod-preview spotify-preview" aria-hidden="true"><div class="mini-player"><div class="mini-player-head">${spotify()}<span>NOW PLAYING</span></div><div class="mini-cover">♫</div><strong>Your next favorite</strong><small>Always within reach</small><div class="mini-playback">◀ <b>Ⅱ</b> ▶</div></div></div>`;}
function request(op,data={}){return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(Error('The client did not respond. Try reopening PME.'));},45000);pending.set(id,{resolve,reject,timer});if(window.webkit?.messageHandlers?.pme)window.webkit.messageHandlers.pme.postMessage({id,op,...data});else{clearTimeout(timer);pending.delete(id);reject(Error('Open this interface from the PimpMyElectron application.'));}});}
window.pmeReceive=response=>{const p=pending.get(response.id);if(!p)return;pending.delete(response.id);clearTimeout(p.timer);response.ok?p.resolve(response.result):p.reject(Error(response.error||'Action failed'));};
function notify(message){toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('visible'),9500);}
async function action(op,data={}){if(busy)return;busy=true;render();try{const result=await request(op,data);if(result?.apps)state=result;}catch(error){notify(error.message);}finally{busy=false;render();}}
function button(label,actionName,style='secondary',glyph){return `<button class="${style}" data-action="${actionName}" ${busy?'disabled':''}>${glyph?icon(glyph):''}${label}</button>`;}
function sidebar(){return `<aside class="sidebar"><div class="brand"><img src="icon.svg" alt="PME"><div><strong>PimpMyElectron</strong><small>Mod manager</small></div></div><button class="nav ${view==='library'?'active':''}" data-view="library">${icon('grid')}Your apps<span class="count">${state?.apps.filter(a=>a.installations.length).length||0}</span></button><div class="sidebar-label">SUPPORTED APPS</div>${(state?.apps||[]).map(a=>`<button class="nav ${view===a.id?'active':''}" data-view="${esc(a.id)}"><span class="slack-small">${appLogo(a.id)}</span>${esc(a.name)}${a.runtime.running?'<span class="count"><i class="dot"></i></span>':''}</button>`).join('')}<div class="sidebar-foot"><button class="nav ${view==='sources'?'active':''}" data-view="sources">${icon('folder')}Mod sources</button><button class="nav ${view==='about'?'active':''}" data-view="about">${icon('info')}About PME</button><p>Local catalog · v${esc(state?.catalogVersion||'0.1.0')}</p></div></aside>`;}
function topbar(title){return `<header class="topbar"><span>Your apps</span>${title?`${icon('chevron')}<span>${esc(title)}</span>`:''}<div class="right">${button('Add app','add-app','quiet','plus')}${button(busy?'Working…':'Rescan','scan','quiet','refresh')}</div></header>`;}
function library(){return `<div class="content"><div class="heading"><div><div class="eyebrow">Your library</div><h1>Your apps. Your way.</h1><p>Choose an app, enable your mods, and make it yours.</p></div></div>${!state?'<div class="skeleton"></div>':`<div class="apps-grid">${state.apps.map(a=>`<button class="app-card" data-view="${esc(a.id)}"><div class="app-art">${appLogo(a.id)}</div><div class="app-card-info"><div class="title"><h2>${esc(a.name)}</h2><span class="tag ${a.installations.length?'green':''}">${a.runtime.running?'Running':a.installations.length?'Detected':'Not installed'}</span></div><p>${esc(a.description)}</p></div><div class="app-card-bottom"><span>${a.mods.length} available mod${a.mods.length!==1?'s':''} · ${a.installations.length} installation${a.installations.length!==1?'s':''}</span>${icon('chevron')}</div></button>`).join('')}</div><p class="library-note">PME supports Slack and Spotify, and looks in Applications and the Mac’s app index. Use Add app for an installation in another location.</p>`}</div><footer class="launchbar"><div class="launch-info"><strong>${busy?'Scanning supported apps…':'Ready when you are'}</strong><small>App bundles stay untouched.</small></div></footer>`;}
function triagePreview(){return `<div class="mod-preview preview-triage" aria-hidden="true"><div class="mini-strip"></div><div class="mini-inbox"><div class="mini-head">Design studio ${icon('compose')}</div><div class="mini-tabs"><b>Unread</b><span>Mentions</span><span>DMs</span><span>Threads</span></div>${[['AL','Alex',''],['#','design','gold'],['JR','Jordan','plum']].map(([initial,name,color])=>`<div class="mini-row"><div class="mini-avatar ${color}">${initial}</div><div class="mini-lines"><b>${name}</b><span></span><span></span></div><div class="mini-dot"></div></div>`).join('')}</div></div>`;}
function quotePreview(){return `<div class="mod-preview preview-reply" aria-hidden="true"><div class="preview-chat"><div class="preview-message"><b>Alex</b><small>10:42</small><p>Let’s ship this tomorrow.</p><div class="preview-actions">↩ Quote&nbsp;&nbsp;▣ Preview</div></div><div class="preview-composer"><span>Replying with preview</span><strong>Let’s ship this tomorrow.</strong><i>Write a reply…</i></div></div></div>`;}
function messagePolishPreview(){return `<div class="mod-preview preview-polish" aria-hidden="true"><div class="preview-chat"><div class="preview-message tint-blue"><b>Alex</b><small>10:42</small><p>Ready for review</p></div><div class="preview-code"><code>const ship = true;</code><b>Copy</b></div><div class="preview-message tint-plum"><b>Jordan</b><small>10:44</small><p>Looks good from here.</p></div></div></div>`;}
function appearancePreview(){return `<div class="mod-preview preview-appearance" aria-hidden="true"><div class="preview-slack"><div class="preview-slack-bar"><i></i><span>Search</span><b>?</b></div><aside><strong>Acme</strong><span class="selected"># launch-ready</span><span># design</span><span>Alex</span></aside><main><b># launch-ready</b><p>Coordinated headers, messages, and composer.</p><div>Message #launch-ready</div></main></div></div>`;}
function customCSSPreview(){return `<div class="mod-preview preview-css" aria-hidden="true"><div class="preview-editor"><div><i></i><i></i><i></i><span>Local stylesheet</span></div><code><b>.c-message</b> {<br>&nbsp;&nbsp;line-height: <em>1.35</em>;<br>&nbsp;&nbsp;border-radius: <em>8px</em>;<br>}</code><small>Live · guarded · recoverable</small></div></div>`;}
function emojiPreview(){return `<div class="mod-preview preview-emoji" aria-hidden="true"><div class="preview-chat"><div class="preview-message"><b>You</b><small>now</small><p>Deploy is ready <span class="preview-big-emoji">🚀</span></p></div><div class="preview-emoji-map"><code>:shipit:</code><span>→</span><b>🚀</b><small>local alias</small></div></div></div>`;}
function sidebarPreview(){return `<div class="mod-preview preview-sidebar" aria-hidden="true"><div class="preview-sidebar-shell"><aside><strong>Priority <small>2</small></strong><span>● Alex</span><span># launch</span><strong>Unified Inbox <small>4</small></strong><span class="selected"># design</span><span>Jordan</span></aside><div class="preview-peek"><b># design</b><p>Latest cached message appears here without fetching.</p><footer><span>Open</span><span>Reply</span></footer></div></div></div>`;}
function layoutPreview(){return `<div class="mod-preview preview-layout" aria-hidden="true"><div class="preview-layout-shell"><div class="preview-layout-top">☰ <span>Search Slack</span> ?</div><aside><b># design</b><span># launch</span><span>Alex</span></aside><main><header># design <i>⌕ ⋯</i></header><p>More room for the conversation.</p><footer>Message #design</footer></main></div></div>`;}
function cameraPreview(){return `<div class="mod-preview camera-preview" aria-hidden="true"><div><span>CAMERA ACTIVE</span><strong>Music paused</strong><div class="camera-apps"><i>Meet</i><i>Zoom</i><i>Browser</i></div><small>Resumes after your chosen delay.</small></div></div>`;}
function externalPreview(){return `<div class="mod-preview external-preview" aria-hidden="true">${icon('folder')}<strong>From your mod source</strong></div>`;}
function modGlyph(mod){return ({triage:'inbox',reply:'quote','message-polish':'wand',appearance:'palette','custom-css':'code','personal-emoji':'smile','sidebar-productivity':'sidebar',layout:'layout','spotify-player':'music','camera-pause':'camera'})[mod.preview]||'grid';}
function modPreview(mod){if(mod.source)return externalPreview();return ({triage:triagePreview,reply:quotePreview,'message-polish':messagePolishPreview,appearance:appearancePreview,'custom-css':customCSSPreview,'personal-emoji':emojiPreview,'sidebar-productivity':sidebarPreview,layout:layoutPreview,'spotify-player':spotifyPreview,'camera-pause':cameraPreview})[mod.preview]?.()||triagePreview();}
function appView(app){const isSpotify=app.id==='spotify',running=app.runtime.running;const triageRunning=!isSpotify&&app.runtime.triageEnabled!==false,triageSelected=!isSpotify&&app.selectedMods.includes('slack-triage'),companionRunning=!isSpotify&&app.runtime.companionEnabled===true,companionSelected=!isSpotify&&app.selectedMods.some(id=>['slack-triage','slack-layout'].includes(id)),companionWanted=app.companionEnabled!==false,companionStatus=companionRunning?'Running with Slack':running&&companionWanted?'Unavailable':companionWanted?'Starts with Slack':'Off';const menuRunning=isSpotify&&(app.runtime.mods||['spotify-menu']).includes('spotify-menu'),cameraRunning=isSpotify&&app.runtime.mods?.includes('spotify-camera-pause');const visibleMods=app.mods.filter(m=>showIncompatible||m.compatible!==false);const selected=app.selectedMods.length,install=app.installations.find(i=>i.path===app.selectedPath);
 return `<div class="content"><div class="hero"><div class="hero-icon">${appLogo(app.id)}</div><div><h1>${esc(app.name)}</h1><p>${esc(app.description)}</p></div><div class="hero-meta"><span class="tag ${install?'green':''}">${running?'<i class="dot"></i>Running':install?'Ready to mod':'Choose an installation'}</span><small>${install?`v${esc(install.version)} · ${install.distribution==='direct-download'?'Direct download':'App Store'}`:'macOS'}</small></div></div>
 ${app.installations.length?`<div class="installation">${icon('folder')}<select id="installation" aria-label="${esc(app.name)} installation" ${busy||running?'disabled':''}>${app.installations.map(i=>`<option value="${esc(i.path)}" ${i.path===app.selectedPath?'selected':''} ${!i.verified?'disabled':''}>${esc(i.path)}${!i.verified?' — could not verify publisher':''}</option>`).join('')}</select><span>Installed app</span></div>`:`<div class="banner"><div><strong>${esc(app.name)} wasn’t found on this Mac.</strong><p>Add your installed ${esc(app.name)} app to get started.</p></div>${button('Find '+app.name+'…','add-app','secondary','folder')}</div>`}
 ${!isSpotify&&companionSelected?`<section class="companion-card"><div>${icon('gear')}<div><strong>Slack Companion</strong><p>${companionWanted?'Optional menu-bar access, global shortcuts, native panels, and one live settings window.':`Companion is off. Configure mods in PME${triageSelected?'; Triage menu-bar controls, global shortcuts, previews, and native backdrop integration are unavailable.':'.'}`}</p></div></div><div class="companion-actions"><span class="tag ${companionRunning?'green':''}">${companionStatus}</span><button class="toggle" role="switch" aria-checked="${companionWanted}" aria-label="Run Slack Companion" data-companion ${busy?'disabled':''}></button>${companionRunning?`<button class="secondary" data-action="companion-settings">Slack settings…</button>`:''}</div></section>`:''}
 ${app.profileConflict?`<div class="banner"><div><strong>Bring your existing PME setup along.</strong><p>Choose your old PME project folder to reuse its settings and sign-ins.</p></div>${button('Import setup','import','secondary')}</div>`:''}
 ${app.changesPending?'<div class="banner"><div><strong>Mod selection changed</strong><p>Your running session is unchanged. Stop and relaunch to apply this selection.</p></div></div>':''}
 ${(app.runtime.externalHelpers||[]).filter(h=>h.state!=='running').map(h=>`<div class="banner">External helper ${esc(h.id||'session')}: ${esc(h.reason||h.state)}</div>`).join('')}${app.runtime.error?`<div class="banner">${esc(app.runtime.error)}</div>`:''}${app.modSettingsError?`<div class="banner">${esc(app.modSettingsError)}</div>`:''}
 <div class="section-title"><h2>Available mods</h2><span>${visibleMods.length}</span><label class="compatibility-filter"><input type="checkbox" id="show-incompatible" ${showIncompatible?'checked':''}> Show incompatible</label></div>
 ${!visibleMods.length?'<p>No compatible mods for this platform. Turn on Show incompatible to explore available ports.</p>':''}${visibleMods.map(m=>`<article class="mod-card ${m.compatible===false?'incompatible':''}"><div class="mod-main"><div class="mod-heading"><div class="mod-mark">${icon(modGlyph(m))}</div><div><h3>${esc(m.name)}<span class="version">${esc(m.version)}</span></h3><div class="mod-author">by ${esc(m.author)} · ${esc(m.source?.name||'Bundled with PME')} · ${esc(m.platforms.map(p=>({mac:'macOS',windows:'Windows',linux:'Linux',global:'All platforms'}[p])).join(', '))}</div></div><button class="toggle" role="switch" aria-checked="${app.selectedMods.includes(m.id)}" aria-label="Enable ${esc(m.name)}" data-mod="${esc(m.id)}" ${busy||m.compatible===false?'disabled':''}></button></div><p>${esc(m.summary||m.description)}</p>${m.compatible===false?`<p class="incompatible-note">${esc(m.compatibilityReason)}</p>`:''}<div class="features">${m.features.slice(0,3).map(f=>`<div class="feature">${icon('check')}${esc(f)}</div>`).join('')}</div><button class="details-button" data-details="${esc(m.id)}">Explore this mod →</button>${m.settings&&app.selectedMods.includes(m.id)?`<button class="secondary mod-settings-button" data-settings="${esc(m.id)}">Configure…</button>`:''}${m.id==='spotify-camera-pause'?`<button class="secondary" data-action="camera-settings" ${busy||!cameraRunning?'disabled':''}>Camera Pause settings…</button>${!cameraRunning?'<p class="setup-hint">Enable this mod and launch Spotify to choose apps.</p>':`<p class="setup-hint">${esc(app.runtime.cameraStatus)}</p>`}`:''}</div>${modPreview(m)}<div class="mod-access">${icon('shield')}${esc(m.access)}</div></article>`).join('')}
 <section class="shortcuts"><div class="section-title"><h2>Manage shortcuts</h2><span>${(app.shortcuts||[]).length}</span></div><p>${app.shortcuts?.length?'Manage the apps you’ve saved for Finder, Spotlight, and the Dock.':'No shortcuts yet. Use Create shortcut below to save this installation and your selected mods as a launcher app.'}</p>
 ${(app.shortcuts||[]).map(p=>`<div class="shortcut-row"><div class="shortcut-info"><strong>${esc(p.name)}</strong><small>${esc(p.modIds.map(id=>app.mods.find(m=>m.id===id)?.name||id).join(', '))}</small><span title="${esc(p.shortcutPath)}">${esc(p.shortcutPath)}</span>${p.availability!=='available'?`<small class="shortcut-status">${p.availability==='missing'?'Not found at its saved location. If moved, launch it once to reconnect.':'Saved location is unavailable.'}</small>`:''}</div><div class="shortcut-actions">${(p.availability==='available'?[['shortcut-reveal','Reveal'],['shortcut-update','Update selection'],['shortcut-rename','Rename'],['shortcut-remove','Remove']]:[['shortcut-forget','Remove from list']]).map(([op,label])=>`<button class="quiet" data-shortcut="${esc(p.id)}" data-shortcut-op="${op}" ${busy?'disabled':''}>${label}</button>`).join('')}</div></div>`).join('')}
 </section>
 ${!isSpotify?`<section class="companion-card"><div>${icon('folder')}<div><strong>Slack settings portability</strong><p>Export or import bundled mod enablement and settings. Profiles, paths, workspaces, messages, Triage activity, and credentials are excluded.</p></div></div><div class="companion-actions"><button class="secondary" data-action="settings-export">Export settings…</button><button class="secondary" data-action="settings-import">Import settings…</button>${app.settingsUndoAvailable?'<button class="quiet" data-action="settings-undo">Undo last bulk change</button>':''}</div></section>`:''}
 </div><footer class="launchbar"><div class="launch-info"><strong>${running?(isSpotify?'Spotify mods are enabled':app.runtime.signedIn?'Slack is running with PME':'Slack is running · sign in to begin'):`${selected} mod${selected===1?'':'s'} enabled`}</strong><small>${running?(isSpotify?(menuRunning?'Hover over Spotify in the menu bar':app.runtime.cameraStatus||'Camera Pause is running'):'Everyday mode · private local connection'):selected?(isSpotify?'Uses your existing Spotify session':'Launches in everyday mode'):'Enable a mod to launch with PME'}</small></div>${running?`<div class="session-actions">${!companionRunning?'':button('Slack settings','mod-settings','quiet','gear')}${button(isSpotify?'Stop mods':'Stop Slack','stop','quiet','stop')}</div>`:''}<div class="launch-actions"><button class="secondary shortcut-callout" data-action="shortcut-create" ${busy||!selected||!install?'disabled':''}>${icon('plus')}Create shortcut…</button>${running?button(isSpotify?(menuRunning?'Open player':'Camera settings'):(triageRunning?'Open inbox':'Open Slack'),'show','primary',isSpotify?'play':'inbox'):`<button class="primary" data-action="launch" ${busy||!selected||!install||app.profileConflict?'disabled':''}>${icon('play')}${busy?'Working…':'Launch '+esc(app.name)}</button>`}</div></footer>`;
}
function aboutOverview(){return `<h2>A home for your app mods.</h2><p>macOS client · ${esc(state?.clientVersion||'…')} (build ${esc(state?.clientBuild||'…')})</p><div class="about-row"><strong>Bundled catalog</strong><p>PME includes a bundled catalog. Add a local folder in Mod sources to install private or community packages. External mods are trusted code; only enable packages from publishers you trust.</p></div><div class="about-row"><strong>Your original apps stay intact</strong><p>PME launches the official app and adds the selected mods for that session. Closing PME leaves a running Slack session available. Stop Slack from its app page to end the session.</p></div><div class="about-row"><strong>A separate Slack sign-in</strong><p>The Slack adapter uses a separate profile. Sign in once inside the PME-launched Slack, or import your existing PME setup on this Mac. Your normal Slack profile is not copied.</p></div><div class="about-row"><strong>Everyday mode</strong><p>The client always uses the existing everyday launcher. Developer evaluation, screenshots, and network experiments are disabled. Spotify uses its native macOS playback controls without a debugging connection. External Slack mods can also run in this mode. Their declared native helpers run as separate processes with their own publisher identity.</p></div><div class="about-row"><strong>Client updates</strong><p>PME checks daily while the manager is running. Updates install only when you choose. Stop mods and quit managed app sessions before installation. Automatic checks can be changed in the PimpMyElectron menu.</p>${button('Check for Updates…','update-check','secondary','refresh')}</div><div class="about-row"><strong>Open source · MPL 2.0</strong><p>PME’s source is available on GitHub. Release source is tagged client-vX.Y.Z for each published version. Bundled dependencies retain their own licenses.</p>${button('View license','license-open','secondary','info')}${button('Source code','source-open','quiet','folder')}</div><div class="about-actions">${button('Import existing setup','import','secondary','folder')}${button('Open data folder','data-folder','quiet','folder')}</div>`;}
// Render the small Markdown subset used by bundled release notes. Escape first;
// notes never execute HTML or open unreviewed remote links in the native view.
function releaseMarkdown(text){
 const inline=s=>esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
 return text.replace(/, or download the ZIP below/g,'').split(/\n\s*\n/).filter(Boolean).map(block=>{
  const lines=block.trim().split('\n');
  if(/^# /.test(lines[0]))return '';
  if(/^## /.test(lines[0]))return '<h3>'+inline(lines[0].slice(3))+'</h3>';
  if(lines.every(l=>/^- /.test(l)))return '<ul>'+lines.map(l=>'<li>'+inline(l.slice(2))+'</li>').join('')+'</ul>';
  return '<p>'+inline(lines.join(' '))+'</p>';
 }).join('');
}
function releasesView(){return `<p>Included with your installed app. Available offline.</p>${historyError?`<p role="alert">${esc(historyError)}</p><button class="secondary" data-action="release-retry">Try again</button>`:!history?'<p role="status">Loading release notes…</p>':history.releases.length?history.releases.map((r,i)=>`<details class="release-entry" ${i===0?'open':''}><summary><strong>Version ${esc(r.version)}</strong>${r.version===history.current?'<span class="tag green">Installed</span>':''}</summary><div class="release-notes">${releaseMarkdown(r.notes)}</div></details>`).join(''):'<p>No release notes were included with this build.</p>'}`;}
async function loadHistory(){historyError=null;try{history=await request('release-history');}catch(e){historyError=e.message;}if(view==='about'&&aboutTab==='releases'){const focused=root.querySelector('[role=tab]:focus')?.dataset.aboutTab;render();if(focused)root.querySelector(`[data-about-tab="${focused}"]`)?.focus();}}
function feedbackReport({kind,area,title,description,versions},snapshot){
 const app=snapshot?.apps.find(a=>a.id===area);
 const lines=[`## ${kind==='idea'?'Idea':'Bug report'}`,`Area: ${app?.name||'PME client'}`,'',description.trim()];
 if(versions){
  lines.push('','## Version details',`PME ${snapshot?.clientVersion||'unknown'} (build ${snapshot?.clientBuild||'unknown'})`,`Platform: ${snapshot?.platform||'mac'}`);
  if(app){const installation=app.installations.find(i=>i.path===app.selectedPath);lines.push(`${app.name}: ${installation?.version||'unknown'}`);
   for(const id of app.selectedMods){const mod=app.mods.find(m=>m.id===id);if(mod&&!mod.source)lines.push(`${mod.name}: ${mod.version}`);}}
 }
 return {title:title.trim(),body:lines.join('\n')};
}
function openFeedback(){
 const d=document.createElement('section');d.className='feedback-panel';d.setAttribute('aria-labelledby','about-title');
 d.innerHTML=`<form class="feedback-form"><label>Type<select name="kind"><option value="bug">Bug report</option><option value="idea">Idea</option></select></label><label>About<select name="area"><option value="client">PME client</option>${(state?.apps||[]).map(a=>`<option value="${esc(a.id)}" ${view===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label>Title<input name="title" required maxlength="120" placeholder="A short summary"></label><label>Details<textarea name="description" required maxlength="2500" rows="6" placeholder="What happened? What did you expect? For a bug, describe how to reproduce it."></textarea></label><label class="feedback-check"><input type="checkbox" name="versions" checked> Include PME, app, and selected bundled mod versions</label><p>Private mod names and source paths, workspace names, messages, account details, and logs are not collected. Please leave private information out of your description.</p><footer><button type="button" data-cancel class="quiet">Clear form</button><button class="primary" type="submit">Review report</button></footer></form><section class="feedback-review" hidden><p>Review the complete report below. Sending publishes this report as a public issue in the PME repository. No GitHub account is needed. Only the text below will be sent.</p><pre></pre><p class="feedback-status" role="status"></p><footer><button class="quiet" data-edit>Edit</button><button class="secondary" data-copy>Copy report</button><button class="primary" data-send>Send feedback</button><button class="quiet" data-cancel>Clear report</button></footer></section>`;
 let report=null,sending=false,sent=false;const form=d.querySelector('form'),review=d.querySelector('.feedback-review'),status=d.querySelector('.feedback-status'),send=d.querySelector('[data-send]');
 const draftKey='pme-feedback-draft';
 const remember=()=>{try{localStorage.setItem(draftKey,JSON.stringify({fields:Object.fromEntries(new FormData(form)),report,sent,reviewing:!review.hidden}));}catch{}};
 const showReview=()=>{review.querySelector('pre').textContent=report.title+'\n\n'+report.body;form.hidden=true;review.hidden=false;send.disabled=sent;send.textContent=sent?'Submitted':'Send feedback';};
 try{const saved=JSON.parse(localStorage.getItem(draftKey));if(saved){for(const [key,value] of Object.entries(saved.fields||{})){const input=form.elements.namedItem(key);if(input&&input.type!=='checkbox')input.value=value;}form.elements.versions.checked=!!saved.fields?.versions;
  if(saved.report&&typeof saved.report.title==='string'&&typeof saved.report.body==='string'&&typeof saved.report.requestId==='string'){report=saved.report;sent=saved.sent===true;if(saved.reviewing)showReview();if(sent)status.textContent='Your previous report was submitted.';}}}catch{}
 form.addEventListener('input',remember);
 form.onsubmit=e=>{e.preventDefault();const fields=new FormData(form),next=feedbackReport({kind:fields.get('kind'),area:fields.get('area'),title:fields.get('title'),description:fields.get('description'),versions:fields.has('versions')},state);if(!next.title||!fields.get('description').trim())return;
  if(!report||report.title!==next.title||report.body!==next.body){report={...next,requestId:Date.now()+'-'+crypto.randomUUID()};sent=false;}
  showReview();status.textContent='';remember();send.focus();};
 d.querySelector('[data-edit]').onclick=()=>{if(sending)return;review.hidden=true;form.hidden=false;remember();form.elements.title.focus();};
 for(const b of d.querySelectorAll('[data-cancel]'))b.onclick=()=>{if(sending)return;form.reset();form.hidden=false;review.hidden=true;report=null;sent=false;status.textContent='';try{localStorage.removeItem(draftKey);}catch{}form.elements.title.focus();};
 d.querySelector('[data-copy]').onclick=async()=>{if(!report)return;try{await request('feedback-copy',report);status.textContent='Report copied.';}catch(e){status.textContent=e.message;}};
 send.onclick=async()=>{
  if(!report||sending||sent)return;sending=true;remember();for(const button of review.querySelectorAll('button'))button.disabled=true;send.textContent='Sending…';status.textContent='Submitting your reviewed report…';
  try{const result=await request('feedback-submit',report);if(result.pending){send.textContent='Check submission';status.textContent='The service is checking whether your report arrived. Use Check submission to check again without creating a duplicate.';}
   else{sent=true;send.textContent='Submitted';status.textContent='Thank you — your report was filed as issue #'+result.url.split('/').pop()+'.';}}
  catch(e){send.textContent='Retry submission';status.textContent=e.message;}
  finally{sending=false;for(const button of review.querySelectorAll('button'))button.disabled=false;send.disabled=sent;remember();}
 };
 return d;
}

const aboutTabs=[['overview','Overview'],['releases','What’s new'],['feedback','Feedback']];
function about(){return `<div class="content"><div class="about"><h1 id="about-title">${aboutTab==='releases'?'What’s new':aboutTab==='feedback'?'Share feedback':'About PME'}</h1><div class="about-tabs" role="tablist" aria-label="About PME">${aboutTabs.map(([id,label])=>`<button type="button" role="tab" id="about-tab-${id}" data-about-tab="${id}" aria-selected="${aboutTab===id}" aria-controls="about-panel" tabindex="${aboutTab===id?0:-1}">${label}</button>`).join('')}</div><section id="about-panel" role="tabpanel" aria-labelledby="about-tab-${aboutTab}" tabindex="0">${aboutTab==='overview'?aboutOverview():aboutTab==='releases'?releasesView():'<div id="feedback-mount"></div>'}</section></div></div>`;}
function selectAboutTab(tab){
 if(!aboutTabs.some(([id])=>id===tab))return;
 aboutTab=tab;render();root.querySelector(`[data-about-tab="${tab}"]`)?.focus();
 if(tab==='releases'&&!history)void loadHistory();
}
function sourcesView(){return `<div class="content"><div class="heading"><div><div class="eyebrow">Your collections</div><h1>Mod sources</h1><p>Add a local folder supplied by your team or a publisher you trust.</p></div></div><div class="source-toolbar">${button('Add folder…','source-add','primary','plus')}${button('Refresh sources','source-refresh','secondary','refresh')}</div><div class="source-card bundled-source"><strong>Bundled with PME</strong><p>Included and updated with the client.</p></div>${(state?.sources||[]).map(s=>`<section class="source-card"><div class="section-title"><h2>${esc(s.name)}</h2><span class="tag">${s.installed?'Installed':'Not installed'}</span></div><p class="source-path">${esc(s.path)}</p>${s.error?`<p role="status">${esc(s.error)}</p>`:''}${s.mods.map(m=>`<div class="source-mod"><strong>${esc(m.name)} <small>${esc(m.version)} · ${esc(m.app)}</small></strong><p>${esc(m.access)}</p>${m.helpers.map(h=>`<p class="helper-publisher">Native helper: ${esc(h.id)} · Apple team ${esc(h.teamId)} · ${esc(h.arch)}${h.serviceOperations?.length?` · service: ${h.serviceOperations.map(esc).join(', ')}`:''}</p>`).join('')}</div>`).join('')}<div class="source-toolbar">${s.updateAvailable?`<button class="primary" data-source="${esc(s.id)}" data-source-op="source-review">${s.installed?'Review update':'Review and install'}</button>`:''}${s.previous?`<button class="secondary" data-source="${esc(s.id)}" data-source-op="source-rollback">Use previous version</button>`:''}<button class="quiet" data-source="${esc(s.id)}" data-source-op="source-remove">Remove source</button></div>${s.installed?'<p class="source-note">Installed files work offline. Changes apply on the next mod session.</p>':''}</section>`).join('')}<p class="library-note">PME never uploads these packages. Your sync tool handles delivery; PME installs complete local copies. New mods start disabled. The first package API supports Slack renderer mods and native helpers.</p></div>`;}
function reviewSource(source){const d=document.createElement('dialog');d.innerHTML=`<h2>Install from ${esc(source.name)}?</h2><p>This installs ${source.mods.length} mod package(s) on this Mac. New mods remain disabled.</p><p>Enabled mods can access data inside their target app. Native helpers run with your user account’s permissions. Trust the people who can change this folder.</p><p>Files are checked for completeness; checksums do not establish who authored them. Helpers must pass macOS publisher and Gatekeeper checks.</p><footer><button class="quiet" data-cancel>Cancel</button><button class="primary" data-install>Install this version</button></footer>`;document.body.append(d);d.querySelector('[data-cancel]').onclick=()=>d.close();d.querySelector('[data-install]').onclick=()=>{d.close();void action('source-install',{sourceId:source.id,digest:source.available});};d.onclose=()=>d.remove();d.showModal();}
function openModSettings(app,mod){
 if(app.runtime.running&&app.runtime.companionEnabled){void action('show',{appId:app.id,view:'preferences',section:mod.id});return;}
 const values=app.modSettings?.[mod.id]||{},d=document.createElement('dialog');d.className='mod-settings-dialog';const form=document.createElement('form');form.innerHTML=`<h2>${esc(mod.name)} settings</h2><p>Changes save on this Mac${app.runtime.running?' and apply to the running Slack session.':'.'}</p><div class="mod-settings-fields"></div><footer><button type="button" class="quiet" data-cancel>Cancel</button><button type="submit" class="primary">Save settings</button></footer>`;const fields=form.querySelector('.mod-settings-fields');
 for(const setting of mod.settings){const row=document.createElement('label');row.className='mod-setting';const title=document.createElement('span');title.textContent=setting.label;let input;if(setting.type==='boolean'){input=document.createElement('input');input.type='checkbox';input.checked=values[setting.key]===true;row.classList.add('check');row.append(input,title);}else{row.append(title);if(setting.type==='select'){input=document.createElement('select');for(const option of setting.options){const item=document.createElement('option');item.value=option.value;item.textContent=option.label;item.selected=values[setting.key]===option.value;input.append(item);}}else if(setting.type==='textarea'){input=document.createElement('textarea');input.rows=9;input.maxLength=setting.maxLength;input.value=values[setting.key]??'';row.classList.add('wide');}else{input=document.createElement('input');input.type=setting.type==='number'?'number':setting.type==='color'?'color':'text';if(setting.type==='number'){input.min=setting.min;input.max=setting.max;input.step=setting.step||1;input.value=values[setting.key]??setting.min;}else{input.value=values[setting.key]??'';if(setting.type==='text')input.maxLength=setting.maxLength;}}row.append(input);}input.name=setting.key;if(setting.description){const note=document.createElement('small');note.textContent=setting.description;row.append(note);}fields.append(row);}
 d.append(form);document.body.append(d);form.querySelector('[data-cancel]').onclick=()=>d.close();form.onsubmit=async event=>{event.preventDefault();const patch={};for(const setting of mod.settings){const input=form.elements.namedItem(setting.key);patch[setting.key]=setting.type==='boolean'?input.checked:setting.type==='number'?Number(input.value):input.value;}for(const button of form.querySelectorAll('button'))button.disabled=true;try{state=await request('mod-settings',{appId:app.id,modId:mod.id,patch});d.close();render();notify('Settings saved.');}catch(error){notify(error.message);for(const button of form.querySelectorAll('button'))button.disabled=false;}};d.onclose=()=>d.remove();d.showModal();
}
async function openSettingsExport(){
 try{const result=await request('settings-export'),d=document.createElement('dialog');d.className='mod-settings-dialog';d.innerHTML=`<form><h2>Export Slack mod settings</h2><p>This JSON contains bundled mod enablement and settings only—no profiles, paths, accounts, workspaces, messages, activity, or credentials.</p><label class="mod-setting wide"><span>Portable settings JSON</span><textarea rows="16" readonly></textarea></label><footer><button type="button" class="secondary" data-select>Select all</button><button type="button" class="primary" data-close>Done</button></footer></form>`;const field=d.querySelector('textarea');field.value=result.text;document.body.append(d);d.querySelector('[data-select]').onclick=()=>{field.focus();field.select();};d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();field.focus();field.select();}catch(error){notify(error.message);}
}
function openSettingsImport(app){
 const d=document.createElement('dialog');d.className='mod-settings-dialog';d.innerHTML=`<form><h2>Import Slack mod settings</h2><p>Paste a PME settings-only export. Nothing changes until you review the preview and confirm.</p><label class="mod-setting wide"><span>Settings JSON</span><textarea name="text" rows="14" maxlength="30000" required></textarea></label><div data-preview></div><footer><button type="button" class="quiet" data-cancel>Cancel</button><button type="submit" class="secondary" data-review>Preview changes</button><button type="button" class="primary" data-apply hidden>Apply settings</button></footer></form>`;const form=d.querySelector('form'),preview=d.querySelector('[data-preview]'),apply=d.querySelector('[data-apply]');let reviewed=null;
 form.querySelector('[data-cancel]').onclick=()=>d.close();form.elements.text.oninput=()=>{reviewed=null;apply.hidden=true;preview.textContent='';};form.onsubmit=async event=>{event.preventDefault();try{const text=form.elements.text.value,result=await request('settings-preview',{text});reviewed=text;preview.innerHTML=result.total?`<p><strong>${result.total} setting${result.total===1?'':'s'} will change.</strong></p><ul>${result.changes.slice(0,40).map(change=>`<li>${esc(changeLabel(app,change))}</li>`).join('')}</ul>${result.total>40?`<p>And ${result.total-40} more.</p>`:''}`:'<p><strong>No settings will change.</strong></p>';apply.hidden=result.total===0;}catch(error){reviewed=null;apply.hidden=true;preview.textContent=error.message;}};apply.onclick=async()=>{if(reviewed!==form.elements.text.value)return;for(const button of form.querySelectorAll('button'))button.disabled=true;try{state=await request('settings-import',{text:reviewed});d.close();render();notify('Settings imported. Undo remains available until the next import.');}catch(error){preview.textContent=error.message;for(const button of form.querySelectorAll('button'))button.disabled=false;}};d.onclose=()=>d.remove();document.body.append(d);d.showModal();form.elements.text.focus();
}
function changeLabel(app,change){const mod=app.mods.find(item=>item.id===change.modId),setting=mod?.settings?.find(item=>item.key===change.key);return `${mod?.name||change.modId} · ${change.key==='enabled'?'Enabled state':setting?.label||change.key}`;}
function configurationHelp(mod){if(mod.settings?.length)return 'Enable the mod, then choose Configure… on its card. When Slack Companion is active, the same controls also appear in Slack Settings and apply live.';if(mod.id==='slack-triage')return 'Triage behavior, appearance, shortcuts, and inbox controls live in Slack Settings while Slack Companion is active.';if(mod.id==='spotify-camera-pause')return 'Enable and launch this mod, then open Camera Pause settings to choose watched apps and the resume delay.';if(mod.id==='spotify-menu')return 'Launch the mod, then use the menu-bar player and its settings for artwork, Mini Library, search, and queue behavior.';return 'Enable the mod on this page, then stop and relaunch the app when PME reports pending selection changes.';}
function openModDetails(app,mod){const dependencies=(mod.requires||[]).map(id=>app.mods.find(item=>item.id===id)?.name||id),settings=mod.settings||[],d=document.createElement('dialog');d.className='mod-details-dialog';d.innerHTML=`<header><div class="mod-mark">${icon(modGlyph(mod))}</div><div><div class="eyebrow">${esc(mod.source?.name||'Built into PME')}</div><h2>${esc(mod.name)} <small>v${esc(mod.version)}</small></h2><p>${esc(mod.summary||mod.description)}</p></div></header><div class="mod-detail-preview">${modPreview(mod)}</div><section><h3>What it does</h3><p>${esc(mod.description||mod.summary)}</p><div class="features">${(mod.features||[]).map(feature=>`<div class="feature">${icon('check')}${esc(feature)}</div>`).join('')}</div></section><section><h3>Configure and use it</h3><p>${esc(configurationHelp(mod))}</p>${settings.length?`<ul class="setting-summary">${settings.map(setting=>`<li><strong>${esc(setting.label)}</strong>${setting.description?`<small>${esc(setting.description)}</small>`:''}</li>`).join('')}</ul>`:''}</section><section class="access-explainer"><h3>Data and access</h3><p>${esc(mod.access)}</p></section><div class="mod-detail-meta"><span>${esc(mod.author)}</span><span>${esc(mod.platforms.map(platform=>({mac:'macOS',windows:'Windows',linux:'Linux',global:'All platforms'}[platform]||platform)).join(', '))}</span>${dependencies.length?`<span>Requires ${esc(dependencies.join(', '))}</span>`:'<span>Works independently</span>'}</div><footer><button class="primary" data-close>Done</button></footer>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();}
function render(){const key=view==='about'?view+':'+aboutTab:view,scroll=renderedView===key?(root.querySelector('.content')?.scrollTop||0):0;const app=state?.apps.find(a=>a.id===view);root.innerHTML=`<div class="shell">${sidebar()}<main class="main">${topbar(app?.name||(view==='about'?'About PME':view==='sources'?'Mod sources':''))}${app?appView(app):view==='about'?about():view==='sources'?sourcesView():library()}</main></div>`;const content=root.querySelector('.content');if(content)content.scrollTop=scroll;renderedView=key;
 if(view==='about'&&aboutTab==='feedback'){feedbackPanel??=openFeedback();root.querySelector('#feedback-mount').append(feedbackPanel);}
}
root.addEventListener('keydown',event=>{
 const tab=event.target.closest('[data-about-tab]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;
 event.preventDefault();const index=aboutTabs.findIndex(([id])=>id===tab.dataset.aboutTab);
 selectAboutTab(aboutTabs[event.key==='Home'?0:event.key==='End'?aboutTabs.length-1:(index+(event.key==='ArrowLeft'?-1:1)+aboutTabs.length)%aboutTabs.length][0]);
});
root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.aboutTab){selectAboutTab(b.dataset.aboutTab);return;}if(b.dataset.view){view=b.dataset.view;render();if(view==='about'&&aboutTab==='releases'&&!history)void loadHistory();return;}const app=state?.apps.find(a=>a.id===view)||state?.apps[0];if(b.dataset.shortcut){void action(b.dataset.shortcutOp,{appId:app.id,profileId:b.dataset.shortcut});return;}if(b.dataset.source){const source=state.sources.find(s=>s.id===b.dataset.source);if(b.dataset.sourceOp==='source-review')reviewSource(source);else void action(b.dataset.sourceOp,{sourceId:source.id});return;}if(b.hasAttribute('data-companion')){void action('companion',{appId:app.id,enabled:app.companionEnabled===false});return;}if(b.dataset.mod){const selected=new Set(app.selectedMods);selected.has(b.dataset.mod)?selected.delete(b.dataset.mod):selected.add(b.dataset.mod);void action('select',{appId:app.id,modIds:[...selected]});return;}
 if(b.dataset.settings){const mod=app.mods.find(item=>item.id===b.dataset.settings);if(mod)openModSettings(app,mod);return;}
 if(b.dataset.details){const mod=app.mods.find(m=>m.id===b.dataset.details);if(mod)openModDetails(app,mod);return;}
 const op=b.dataset.action;if(!op)return;if(op==='release-retry'){void loadHistory();return;}if(op==='settings-export'){void openSettingsExport();return;}if(op==='settings-import'){openSettingsImport(app);return;}if(op==='settings-undo'){void action('settings-undo');return;}const map={'show':'show','mod-settings':'show','companion-settings':'show','camera-settings':'show'};
 void action(map[op]||op,{...(app?{appId:op==='import'?'slack':app.id}:{}),...(op==='show'?{view:'queue'}:['mod-settings','companion-settings'].includes(op)?{view:'preferences'}:op==='camera-settings'?{view:'camera-settings'}:{})});});
root.addEventListener('change',event=>{if(event.target.id==='show-incompatible'){showIncompatible=event.target.checked;render();return;}if(event.target.id==='installation')void action('select',{appId:view,installationPath:event.target.value});});
render();void action('scan');
setInterval(async()=>{if(busy||document.querySelector('dialog[open]')||document.activeElement?.matches('select'))return;try{const next=await request('status');if(JSON.stringify(next)!==JSON.stringify(state)){state=next;if(view!=='about')render();}}catch{}},2500);
