(()=>{
  'use strict';
  if(window.__PME_PERSONAL_EMOJI__||location.origin!=='https://app.slack.com')return;
  const STYLE_ID='pme-personal-emoji-style',messageSelector='[data-qa="message_content"],.c-message_kit__text',blockedSelector='code,pre,a,[contenteditable="true"],[data-pme-personal-emoji]';
  let aliases=new Map(),personalAliases=new Map(),disposed=false,scheduled=false,frame=0,replacements=0;const failed=new Set(),providers=new Map(),resolvedImages=new Map(),resolvingImages=new Set();
  function safeURL(value){try{const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443'||url.href.length>500)return null;const host=url.hostname.toLowerCase();if(!host.includes('.')||host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host.endsWith('.internal')||host.endsWith('.home.arpa')||host.includes(':'))return null;const parts=host.split('.');if(parts.every(part=>/^\d+$/.test(part))){const o=parts.map(Number);if(o.length!==4||o.some(n=>n<0||n>255)||o[0]===10||o[0]===127||o[0]===0||o[0]===169&&o[1]===254||o[0]===172&&o[1]>=16&&o[1]<=31||o[0]===192&&o[1]===168)return null;}return url.href;}catch{return null;}}
  function parse(value){if(typeof value!=='string'||value.length>8000)return null;const map=new Map();for(const raw of value.split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const match=line.match(/^((?::[a-z0-9][a-z0-9_+-]{1,39}:\s+)+)(\S+)$/i),url=match&&safeURL(match[2]),names=match?[...match[1].matchAll(/:([a-z0-9][a-z0-9_+-]{1,39}):/gi)].map(item=>item[1].toLowerCase()):[];if(!url||!names.length||names.length>11||names.some(name=>map.has(name))||map.size+names.length>50)return null;for(const name of names)map.set(name,url);}return map;}
  function restore(){for(const image of document.querySelectorAll('[data-pme-personal-emoji]')){const parent=image.parentNode;image.replaceWith(document.createTextNode(image.alt||`:${image.dataset.pmePersonalEmoji||''}:`));replacements=Math.max(0,replacements-1);parent?.normalize();}}
  function rebuildAliases(){const next=new Map();for(const provider of providers.values())for(const [name,entry] of provider.aliases)if(!next.has(name))next.set(name,entry);for(const [name,url] of personalAliases)next.set(name,{url,resolver:null});aliases=next;}
  function providerEntries(value){if(!Array.isArray(value)||value.length>1000)return null;const map=new Map(),namePattern=/^[a-z][a-z0-9_+-]{1,63}$/;for(const raw of value){if(!raw||typeof raw!=='object')return null;const name=String(raw.name||raw.shortcode||'').replace(/^:+|:+$/g,'').toLowerCase(),url=safeURL(raw.imageUrl||raw.image_url||raw.url),rawAliases=Array.isArray(raw.aliases)?raw.aliases:[];if(!namePattern.test(name)||!url||rawAliases.length>10)return null;const names=[name,...rawAliases.map(value=>String(value).replace(/^:+|:+$/g,'').toLowerCase())];if(names.some(value=>!namePattern.test(value)))return null;const entry={url};for(const value of names)if(!map.has(value))map.set(value,entry);}return map;}
  function resolveProviderImage(entry){if(!entry.resolver)return entry.url;const ready=resolvedImages.get(entry.url);if(ready)return ready;if(resolvingImages.has(entry.url)||failed.has(entry.url))return null;resolvingImages.add(entry.url);Promise.resolve().then(()=>entry.resolver(entry.url)).then(value=>{const resolved=typeof value==='string'&&(/^data:image\/[a-z0-9.+-]+;base64,[a-z0-9+/=]+$/i.test(value)&&value.length<=750000||safeURL(value));if(resolved){resolvedImages.set(entry.url,value);schedule();}else failed.add(entry.url);},()=>failed.add(entry.url)).finally(()=>resolvingImages.delete(entry.url));return null;}
  function markJumbo(container){if(!container)return;const images=[...container.querySelectorAll('[data-pme-personal-emoji]')];for(const image of images)image.removeAttribute('data-pme-personal-emoji-large');if(!images.length||images.length>3)return;const clone=container.cloneNode(true);clone.querySelectorAll('[data-pme-personal-emoji]').forEach(image=>image.remove());if(clone.textContent.replace(/[\u200b-\u200d\ufeff]/g,'').trim())return;for(const image of images)image.setAttribute('data-pme-personal-emoji-large','');}
  function replaceText(node){
    if(!node.nodeValue?.includes(':')||node.parentElement?.closest(blockedSelector)||!node.parentElement?.closest(messageSelector))return;
    const pattern=/:([a-z0-9][a-z0-9_+-]{1,63}):/gi,fragment=document.createDocumentFragment();let last=0,changed=false,match;
    while((match=pattern.exec(node.nodeValue))){const name=match[1].toLowerCase(),entry=aliases.get(name),url=entry&&resolveProviderImage(entry);if(!url||failed.has(entry.url))continue;fragment.append(node.nodeValue.slice(last,match.index));const image=document.createElement('img');image.setAttribute('data-pme-personal-emoji',name);image.alt=`:${name}:`;image.title=image.alt;image.src=url;image.loading='lazy';image.decoding='async';image.referrerPolicy='no-referrer';image.addEventListener('error',()=>{failed.add(entry.url);const parent=image.parentNode,container=parent?.closest?.(messageSelector);image.replaceWith(document.createTextNode(image.alt));replacements=Math.max(0,replacements-1);parent?.normalize();markJumbo(container);},{once:true});fragment.append(image);last=pattern.lastIndex;changed=true;replacements++;}
    if(changed){const container=node.parentElement?.closest(messageSelector);fragment.append(node.nodeValue.slice(last));node.replaceWith(fragment);markJumbo(container);}
  }
  function scan(root=document){if(disposed||!aliases.size)return;const containers=[];if(root.nodeType===1&&root.matches?.(messageSelector))containers.push(root);if(root.nodeType===1||root.nodeType===9)containers.push(...root.querySelectorAll(messageSelector));for(const container of containers){const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes)replaceText(node);}}
  function schedule(root=document){if(scheduled||disposed)return;scheduled=true;frame=requestAnimationFrame(()=>{scheduled=false;scan(root);});}
  const style=document.createElement('style');style.id=STYLE_ID;style.textContent='[data-pme-personal-emoji]{display:inline-block!important;width:22px!important;height:22px!important;max-width:22px!important;max-height:22px!important;margin:0 .08em!important;vertical-align:-5px!important;object-fit:contain!important;border-radius:2px}[data-pme-personal-emoji-large]{width:32px!important;height:32px!important;max-width:32px!important;max-height:32px!important}';(document.head||document.documentElement).append(style);
  const observer=new MutationObserver(records=>{if(records.some(record=>[...record.addedNodes].some(node=>node.nodeType===1||node.nodeType===3)))schedule();});observer.observe(document.body,{subtree:true,childList:true,characterData:true});
  function configure(value={}){const parsed=parse(value.definitions??'');if(!parsed)throw Error('Invalid personal emoji definitions.');restore();personalAliases=parsed;rebuildAliases();failed.clear();schedule();return {aliases:aliases.size,replacements};}
  function registerProvider(id,entries,resolveImage){if(typeof id!=='string'||!/^[a-z0-9][a-z0-9-]{0,63}$/.test(id)||typeof resolveImage!=='function')throw Error('Invalid emoji provider.');const parsed=providerEntries(entries);if(!parsed)throw Error('Invalid emoji provider entries.');restore();providers.set(id,{aliases:new Map([...parsed].map(([name,entry])=>[name,{...entry,resolver:resolveImage}]))});rebuildAliases();failed.clear();schedule();return ()=>{if(!providers.has(id))return;restore();providers.delete(id);rebuildAliases();for(const entry of parsed.values())resolvedImages.delete(entry.url);schedule();};}
  function dispose(){if(disposed)return;disposed=true;observer.disconnect();if(frame)cancelAnimationFrame(frame);restore();style.remove();aliases.clear();personalAliases.clear();providers.clear();resolvedImages.clear();resolvingImages.clear();failed.clear();delete window.__PME_PERSONAL_EMOJI__;}
  window.__PME_PERSONAL_EMOJI__={version:'0.3.0',configure,registerProvider,status:()=>({aliases:aliases.size,providers:providers.size,replacements}),dispose};
})();
